project:
  type: website

website:
  title: "Biostatistics - Spring 2025"
  navbar:
    collapse: false
    right:
      - syllabus.qmd
      - index.qmd
      - icon: github
        href: https://github.com/samanthaseals/STA4173Sp25TR
  search: false

format:
  html:
    anchor-sections: false
    title-block: false
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

