---
page-layout: full
title: "Syllabus"
format:
  html:
    embed-resources: true
execute:
    echo: false
    warning: false
    message: false
---

Note: this is an abbreviated syllabus. The full syllabus is available through Classmate and/or Canvas.

### Instructor Information

- [Dr. Samantha Seals](http://sealslab.github.io)
-	Office: 4/344

### Meeting Times and Location

-	TR 2:30-3:45 pm
- Classroom: 4/310

### Office Hours

- Monday: 2:30--4:30 pm (Central)
- Wednesday: 2:30--4:30 pm (Central)
- Thursday: 10:00 am--12:00 pm (Central)
- Other times by appointment

### Grading and Evaluation

The course grade will be determined as follows:

1. Assignments (25%): Each module will include an activity for students to complete using Quarto and R. The resulting .html file should be submitted to the designated dropbox on Canvas by 11:59 pm on the specified date. 
    - Assignment 0: due S 01/12
    - Assignment 1: due S 01/26
    - Assignment 2: due S 02/09
    - Assignment 3: due S 03/16
    - Assignment 4: due S 04/27
2. Projects - 2 (20% each): You will work with your research team to complete two projects. Deliverables will include a written report and an oral presentation.
    - Project 1: write up due W 02/19; presentation 02/27
    - Project 2: write up due W 04/02; presentation 04/03
3. OUR Symposium (10%): Each team will put together a research poster based on Projects 1 and 2. To replace class on Thursday, 04/17, everyone will be presenting their poster at the symposium. 
4. Final Exam (25%): The final exam will be a timed concepts-based exam. While there may be some calculations needed, you will not be processing raw data. The final exam will be *in class* 2:00-4:30 pm on April 29, 2025.

### Late Policy 

Assigments have due dates, however, the dropboxes will not close until the end of the semester. All students are automatically granted "extensions" without question. 

Note that if there is not a submission when I go to grade (after the initial deadline), I will assign a zero (0) and request that you submit the assignment when you are able to. This is only for record keeping purposes. There is no penalty for submitting late and a full grade will be given upon review of your submission.

**Extensions are *not available* for the projects or final exam**.

### Important University Dates

Date|Event
---|---
Jan 8 (Mon) | Spring begins.
Jan 14 (Tues) | Drop/Add period ends.
Jan 20 (Mon) | Martin Luther King's birthday - **campus closed**.
Mar 17-23 (Mon-Fri) | Spring Break - **campus closed**.
Apr 7 (Mon) | Withdrawal deadline (automatic grade of "W").
May 5 (Fri) | Late withdrawal deadline ("W" or "WF", see requirements below).
