{
  "hash": "7bab3c0dc1782f947bd30f94cf689a28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**Tests for Proportions**\"\nsubtitle: \"**STA4173: Biostatistics** <br> Spring 2025\"\nformat: \n  revealjs: \n    code-overflow: wrap\n    df-print: paged\n    embed-resources: true\n    slide-number: true\n    width: 1600\n    height: 900\n    html-math-method: katex\n    theme:\n      - default\nexecute:\n  echo: true\n  warning: false\n  message: false\n  error: true\neditor: source\n---\n\n\n\n## Introduction\n\n- Before today, we have focused on continuous outcomes.\n\n- Now we will focus on categorical (or qualitative) outcomes.\n\n- Today, we will review how to test one and two sample proportions.\n\n- We will estimate a proportion using $\\hat{p}$, \n\n$$\\hat{p} = \\frac{x}{n}$$\n    \n- We will estimate the difference between two proportions using $\\hat{p}_1 - \\hat{p}_2$, \n\n$$\\hat{p_1}- \\hat{p_2} = \\frac{x_1}{n_1} - \\frac{x_2}{n_2}$$\n\n## One-Sample Proportions {.smaller}\n\n- Hypotheses\n    - $H_0:$ $p \\ge p_0$ $|$ $H_0:$ $p \\le p_0$ | $H_0:$ $p = p_0$\n    - $H_1:$ $p < p_0$ | $H_0:$ $p > p_0$ | $H_1:$ $p \\ne p_0$ \n\n- Test Statistic\n\n$$\nz_0 = \\frac{\\hat{p}-p_0}{\\sqrt{\\frac{p_0(1-p_0)}{n}}}\n$$\n\n- *p*-Value\n    - $p = P[z \\le z_0]$ | $p = P[z \\ge z_0]$ | $p = 2P[z \\ge |z_0|]$\n\n- Rejection Region\n    - Reject $H_0$ if $p < \\alpha$.\n\n- Conclusion/Interpretation\n    - [Reject or fail to reject] $H_0$.\n    - There [is or is not] sufficient evidence to suggest [alternative hypothesis in words].\n\n## One-Sample Proportions\n\n- **(1--$\\alpha$)100% CI for a population proportion, $p$**\n\n$$\\hat{p} \\pm z_{\\alpha/2} \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\n- To construct this interval, we require both:\n    - $n\\hat{p}(1-\\hat{p}) \\ge 10$ and \n    - $n \\le 0.05N$\n    \n## One-Sample Proportions\n\n- We will use either the [`binom.test()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/binom.test) function or the [`prop.test()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/prop.test) function.\n\n- If we have $n \\le 30$,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x = num_success, \n           n = sample_size, \n           p = hypothesized_value, \n           alternative = \"alternative\")\n```\n:::\n\n\n\n- If we have $n > 30$,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = num_success, \n          n = sample_size, \n          p = hypothesized_value, \n          alternative = \"alternative\",\n          correct=FALSE)\n```\n:::\n\n\n\n## One-Sample Proportions\n\n- Humira is a medication used to treat rheumatoid arthritis (RA). In clinical trials of Humira, 705 subjects diagnosed with RA were administered 40 mg of Humira every other week. Of the 705 subjects, 66 reported nausea as a side effect. It is known that the proportion of RA subjects in similar studies receiving a placebo who report nausea as a side effect is 0.08. Does the sample evidence represent significant evidence that a higher proportion of subjects receiving Humira experience nausea as a side effect than those taking a placebo? Test at the $\\alpha = 0.05$ level of significance.\n\n- **What are the important pieces?**\n\n## One-Sample Proportions\n\n- Humira is a medication used to treat rheumatoid arthritis (RA). In clinical trials of Humira, 705 subjects diagnosed with RA were administered 40 mg of Humira every other week.  Of the <font color=\"#db0b9d\">705 subjects</font>, <font color=\"#db0b9d\">66 reported nausea as a side effect</font>. It is known that the proportion of RA subjects in <font color=\"#db0b9d\">similar studies receiving a placebo who report nausea as a side effect is 0.08</font>. Does the sample evidence represent significant evidence that a higher proportion of subjects receiving Humira experience nausea as a side effect than those taking a placebo? Test at the $\\alpha = 0.05$ level of significance.\n\n- What is the point estimate, \\boldmath $\\hat{p}$?\n\n- What is the 95% confidence interval for $p$?\n\n- Are there a higher proportion of subjects taking Humira experiencing nausea as a side effect than those taking a placebo?\n\n## One-Sample Proportions\n\n- Of the <font color=\"#db0b9d\">705 subjects</font>, <font color=\"#db0b9d\">66 reported nausea as a side effect</font>. It is known that the proportion of RA subjects in <font color=\"#db0b9d\">similar studies receiving a placebo who report nausea as a side effect is 0.08</font>. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 66, \n          n = 705,\n          alternative = \"two\",\n          correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  66 out of 705, null probability 0.5\nX-squared = 465.71, df = 1, p-value < 2.2e-16\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.07426251 0.11737620\nsample estimates:\n         p \n0.09361702 \n```\n\n\n:::\n:::\n\n\n\n- Thus, the point estimate is $\\hat{p} = 0.094$ and the 95% CI for $p$ is $(0.07, 0.12)$.\n\n## One-Sample Proportions\n\n- Of the <font color=\"#db0b9d\">705 subjects</font>, <font color=\"#db0b9d\">66 reported nausea as a side effect</font>. It is known that the proportion of RA subjects in <font color=\"#db0b9d\">similar studies receiving a placebo who report nausea as a side effect is 0.08</font>. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 66, \n          n = 705,\n          p = 0.08,\n          alternative = \"greater\",\n          correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  66 out of 705, null probability 0.08\nX-squared = 1.7761, df = 1, p-value = 0.09131\nalternative hypothesis: true p is greater than 0.08\n95 percent confidence interval:\n 0.07709288 1.00000000\nsample estimates:\n         p \n0.09361702 \n```\n\n\n:::\n:::\n\n\n\n## One-Sample Proportions {.smaller}\n\n- **Hypotheses:**\n\n    - $H_0: \\ p \\le 0.08$ \n    - $H_1: \\ p > 0.08$\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2 = 1.77$\n    - $p= 0.091$\n    \n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$.\n\n- **Conclusion / Interpretation**\n\n    - Fail to reject $H_0$. \n    \n    - There is not sufficient evidence to suggest that the proportion of subjects taking Humira who experience nausea is greater than 0.08.\n\n## One-Sample Proportions\n\n- Which do you think is easier to raise -- a boy or a girl? When asked this question in 1947, 24\\% of all Americans said raising a girl was easier. In June 2018, the Gallup Organization surveyed 1500 adult Americans, of which 408 felt it was easier to raise a girl. Does this result suggest the proportion of adult Americans who believe it is easier to raise a girl has changed since 1947? Test at the $\\alpha=0.10$ level.\n\n- **What are the important pieces?**\n\n## One-Sample Proportions\n\n- Which do you think is easier to raise -- a boy or a girl? When asked this question in 1947, 24\\% of all Americans said raising a girl was easier. In June 2018, the Gallup Organization surveyed 1500 adult Americans, of which 408 felt it was easier to raise a girl. Does this result suggest the proportion of adult Americans who believe it is easier to raise a girl has changed since 1947? Test at the $\\alpha=0.10$ level.\n\n- **What are the important pieces?**\n    - Which do you think is easier to raise -- a boy or a girl? When asked <font color=\"#db0b9d\">this question in 1947, 24\\%</font> of all Americans said raising a girl was easier. In June 2018, the Gallup Organization <font color=\"#db0b9d\">surveyed 1500 adult Americans</font>, of which <font color=\"#db0b9d\">408 felt it was easier</font> to raise a girl.  Does this result suggest the proportion of adult Americans who believe it is easier to raise a girl has changed since 1947?  Test at the $\\alpha=0.10$ level.\n\n\n## One-Sample Proportions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 408, \n          n = 1500,\n          p = 0.24,\n          correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  408 out of 1500, null probability 0.24\nX-squared = 8.4211, df = 1, p-value = 0.003709\nalternative hypothesis: true p is not equal to 0.24\n95 percent confidence interval:\n 0.2500845 0.2950804\nsample estimates:\n    p \n0.272 \n```\n\n\n:::\n:::\n\n\n\n- Thus, the point estimate is $\\hat{p} = 0.272$ and the 95% CI for $p$ is $(0.25, 0.30)$.\n\n## One-Sample Proportions {.smaller}\n\n- **Hypotheses**\n\n    - $H_0: \\ p = 0.24$ \n    - $H_1: \\ p \\ne 0.24$\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2 = 8.42$ \n    - $p= 0.004$\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.10$.\n\n- **Conclusion / Interpretation**\n\n    - Reject $H_0$. \n    \n    - There is sufficient evidence to suggest that the proportion of adult Americans who believe that it is easier to raise a girl has changed since 1947.\n    \n## Two-Sample Proportions {.smaller}\n\n- **Hypotheses**\n    - $H_0:$ $p_1 - p_2 \\ge d_0$ $|$ $H_0:$ $p_1 -p_2 \\le d_0$ | $H_0:$ $p_1-p_2 = d_0$\n    - $H_1:$ $p_1-p_2 < d_0$ | $H_0:$ $p_1 - p_2 > d_0$ | $H_1:$ $p_1-p_2 \\ne d_0$ \n    \n- **Test Statistic**\n\n$$z_0 = \\frac{\\left( \\hat{p}_1 - \\hat{p}_2 \\right)- d_0}{\\sqrt{\\hat{p}\\left(1-\\hat{p}\\right)\\left( \\frac{1}{n_1}+\\frac{1}{n_2} \\right)}}$$\n\n- where \n\n$$\\hat{p}_1 = \\frac{x_1}{n_1}, \\ \\ \\ \\hat{p}_2 = \\frac{x_2}{n_2}, \\ \\ \\ \\hat{p} = \\frac{x_1+x_2}{n_1+n_2}$$\n\n- *p*-Value\n    - $p = P[z \\le z_0]$ | $p = P[z \\ge z_0]$ | $p = 2P[z \\ge |z_0|]$\n\n- Rejection Region\n    - Reject $H_0$ if $p < \\alpha$.\n\n\n\n## Two-Sample Proportions {.smaller}\n\n- **(1--$\\alpha$)100% CI for $p_1-p_2$** \n\n$$(\\hat{p}_1 - \\hat{p}_2) \\pm z_{\\alpha/2} \\sqrt{\\frac{\\hat{p}_1 (1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}}$$ \n\n- where\n\n$$\\hat{p}_1-\\hat{p}_2=\\frac{x_1}{n_1} - \\frac{x_2}{n_2}$$\n\n- and\n    - $x_i$ is the number of individuals in group $i$ with a specified characteristic\n    - $n_i$ is the sample size for group $i$\n\n- To construct this interval, we require: \n\n    - $n_1 \\hat{p}_1(1-\\hat{p}_1) \\ge 10$ and \n    - $n_2 \\hat{p}_2(1-\\hat{p}_2) \\ge 10$.\n\n## Two-Sample Proportions\n\n- In R, we again use the [`prop.test()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/prop.test) function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(count_1, count_2), \n          n = c(n_1, n_2), \n          alternative = \"alternative\",\n          correct=FALSE)\n```\n:::\n\n\n\n## Two-Sample Proportions\n\n- In clinical trials of Nasonex, 3774 adult and adolescent allergy patients (patients 12 years and older) were randomly divided into two groups. \n\n    - The patients in group 1 (experimental group) received 200 $\\mu$g of Nasonex.\n    \n        - Of the 2103 patients in the experimental group, 547 reported headaches as a side effect.\n    \n    - The patients in group 2 (control group) received a placebo.  \n    \n        - Of the 1671 patients in the control group, 368 reported headaches as a side effect. \n        \n- Is there evidence to conclude that the proportion of Nasonex users who experienced headaches as a side effect is greater than the proportion in the control group?\n\n- Test at the $\\alpha= 0.05$ level of significance.\n\n- **What are the important pieces?**\n\n## Two-Sample Proportions\n\n- In clinical trials of Nasonex, 3774 adult and adolescent allergy patients (patients 12 years and older) were randomly divided into two groups. \n\n    - The patients in <font color=\"#db0b9d\">group 1</font> (experimental group) received 200 $\\mu$g of Nasonex.\n    \n        - Of the <font color=\"#db0b9d\">2103 patients</font> in the experimental group, <font color=\"#db0b9d\">547 reported headaches as a side effect</font>.\n    \n    - The patients in <font color=\"#db0b9d\">group 2</font> (control group) received a placebo.  \n    \n        - Of the <font color=\"#db0b9d\">1671 patients</font> in the control group, <font color=\"#db0b9d\">368 reported headaches as a side effect</font>. \n        \n- Is there evidence to conclude that the proportion of Nasonex users who experienced headaches as a side effect is greater than the proportion in the control group?\n\n- Test at the $\\alpha= 0.05$ level of significance.\n\n- **What are the important pieces?**\n\n## Two-Sample Proportions\n\n- Of the <font color=\"#db0b9d\">2103 patients</font> in the experimental group, <font color=\"#db0b9d\">547 reported headaches as a side effect</font>.\n\n- Of the <font color=\"#db0b9d\">1671 patients</font> in the control group, <font color=\"#db0b9d\">368 reported headaches as a side effect</font>. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(547, 368), \n          n = c(2103, 1671), \n          correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(547, 368) out of c(2103, 1671)\nX-squared = 8.0618, df = 1, p-value = 0.004521\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.01255827 0.06719613\nsample estimates:\n   prop 1    prop 2 \n0.2601046 0.2202274 \n```\n\n\n:::\n:::\n\n\n- Thus, $\\hat{p}_{\\text{Exp}} = 0.260$, $\\hat{p}_{\\text{Ctrl}} = 0.220$ and $\\hat{p}_{\\text{Exp}} - \\hat{p}_{\\text{Ctrl}} = 0.04$.\n\n- The 95% CI for $\\hat{p}_{\\text{Exp}} - \\hat{p}_{\\text{Ctrl}}$ is $(0.013, 0.067)$.\n\n## Two-Sample Proportions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(547, 368), \n          n = c(2103, 1671), \n          alternative = \"greater\",\n          correct=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(547, 368) out of c(2103, 1671)\nX-squared = 8.0618, df = 1, p-value = 0.00226\nalternative hypothesis: greater\n95 percent confidence interval:\n 0.01695043 1.00000000\nsample estimates:\n   prop 1    prop 2 \n0.2601046 0.2202274 \n```\n\n\n:::\n:::\n\n\n\n## Two-Sample Proportions {.smaller}\n\n- **Hypotheses**\n\n    - $H_0: \\ p_{\\text{Exp}} \\le p_{\\text{Ctrl}}$  \n    - $H_1: \\ p_{\\text{Exp}} > p_{\\text{Ctrl}}$ \n\n- **Test Statistic and *p*-value**\n\n    - $\\chi^2 = 8.06$ or $z_0 = \\sqrt{8.0618} = 2.839$\n    - $p= 0.002$\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$.\n\n- **Conclusion / Interpretation**\n\n    - Reject $H_0$. \n    \n    - There is sufficient evidence to suggest that the proportion of Nasonex users who experienced headaches as a side effect is greater than that of the control group.\n\n## Goodness-of-Fit\n\n- The goodness-of-fit test allows us to determine if a frequency distribution follows a specific distribution.\n\n    - This could be a named distribution (e.g., normal)\n\n    - It could also be a distribution without a name (e.g., the probabilities are specified)\n\n- Before we can perform the goodness-of-fit test, we must compute expected counts.$$E_i = n p_i$$\n\n    - e.g., suppose that we expect 25\\% of Skittles to be red; if we have 100 Skittles, we then expect 25 of them to be red.\n    \n## Goodness-of-Fit\n\n- **Hypotheses**\n\n    - $H_0:$ The random variable follows the specified distribution.\n    - $H_1:$ The random variable does not follow the specified distribution.\n\n- **Test Statistic**\n\n    - $\\chi^2_0 = \\sum_{i=1}^k \\frac{(O_i-E_i)^2}{E_i}$, where $O_i$ = observed and  $E_i$ = expected\n\n- ***p*-Value**\n    - $p = P[\\chi^2_{k-1} \\ge \\chi^2_0]$, where $k$ = number of categories\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$\n\n## Goodness-of-Fit\n\n- In R, we will use the `chisq.test()` function and plug in both the counts and the expected probabilities\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- c(count_1, count_2, ... , count_k) # create O_i vector\nprobs <- c(prob_1, prob_2, ..., prob_k) # create p_i vector\nchisq.test(counts, p = probs)\n```\n:::\n\n\n\n## Goodness-of-Fit {.smaller}\n\n- Using the economy data, below (based on the 2017 Current Population Survey, adjusted for inflation), determine if there is evidence to suggest that the distribution of income has changed since 2000. \n\n- Test at the $\\alpha = 0.05$ level of significance.\n\n| Income | Observed | Probability |\n|-|:-:|:-:|\n| Under \\$15,000 | 161 | 0.099 |\n| \\$15,000 - \\$24,999 | 144 | 0.098 |\n| \\$25,000 - \\$34,999 | 138 | 0.093 |\n| \\$35,000 - \\$49,999 | 184 | 0.135 |\n| \\$50,000 - \\$74,999 | 247 | 0.179 |\n| \\$75,000 - \\$99,999 | 188 | 0.131 |\n| \\$100,000 - \\$149,999 | 217 | 0.149 |\n| \\$150,000 - \\$199,999 | 105 | 0.061 |\n| Over \\$200,000 | 116 | 0.055 |\n\n## Goodness-of-Fit\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- c(161, 144, 138, 184, 247, 188, 217, 105, 116) # create O_i vector\nprobs <- c(0.099, 0.098, 0.093, 0.135, 0.179, 0.131, 0.149, 0.061, 0.055) # create p_i vector\nchisq.test(counts, p = probs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  counts\nX-squared = 20.693, df = 8, p-value = 0.00801\n```\n\n\n:::\n:::\n\n\n\n## Goodness-of-Fit {.smaller}\n\n- **Hypotheses**\n\n    - $H_0:$ Distribution of income in 2017 follows the same distribution as 2000.\n    - $H_1:$ Distribution of income in 2017 does not follow the same distribution as 2000.\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2_0 = 20.693$ \n    - $p = 0.008$\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$\n\n- **Conclusion/Interpretation**\n\n    - Reject $H_0$. \n    \n    - There is sufficient evidence to suggest that the distribution of income in 2017 does not follow the same distribution as in 2000.\n    \n## Goodness-of-Fit\n\n- An obstetrician wants to know whether the proportion of children born on each day of the week is the same. \n\n- She randomly selects 500 birth records and obtains the data shown in the table below (based on data obtained from Vital Statistics of the United States, 2016). \n\n- Is there reason to believe that the day on which a child is born does not occur with equal frequency at the $\\alpha = 0.01$ level of significance?\n\n| Sun | Mon | Tues | Weds | Thurs | Fri | Sat |\n|:-:|:-:|:-:|:-:|:-:|:-:|:-:|\n| 46 | 76 | 83 | 81 | 81 | 80 | 53 |\n\n- What about expected probabilities?\n\n## Goodness-of-Fit\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- c(46, 76, 83, 81, 81, 80, 53) # create O_i vector\nprobs <- c(1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7) # create p_i vector\nchisq.test(counts, p = probs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  counts\nX-squared = 19.568, df = 6, p-value = 0.003305\n```\n\n\n:::\n:::\n\n\n\n## Goodness-of-Fit {.smaller}\n\n- **Hypotheses**\n\n    - $H_0: \\ p_M = p_T = ... = p_{Su} = \\frac{1}{7}$.\n    - $H_1:$ At least one proportion is different.\n\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2_0 = 19.568$\n    - $p = 0.003$\n    \n- **Rejection Region**\n\n  - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.01$\n\n- **Conclusion/Interpretation**\n\n    - Reject $H_0$.\n    - There is sufficient evidence to suggest that at least one proportion is different.\n    \n## Test for Independence\n\n- Let us now discuss testing two categorical variables to determine if a relationship exists. \n\n- Take, for example, this data:\n<center><img src = \"images/L18a.png\"></center>\n\n- We will use the $\\chi^2$ test for independence to determine if happiness depends on marital status. \n    \n## Test for Independence\n\n- Like in the goodness-of-fit test, we will first compute expected values.\n\n<center><img src = \"images/L18b.png\" width = 1000></center>\n\n- We find the expected values,\n\n$$E_{ij} = \\frac{R_i C_j}{n}$$ \n\n- where $R_i$ is the total for row $i$, $C_j$ is the total for column $j$, and $n$ is the total sample size\n\n## Test for Independence\n\n- **Hypotheses**\n\n    - $H_0$: There is not a relationship between [var 1] and [var 2].\n    - $H_1$: There is a relationship between [var 1] and [var 2].\n\n- **Test Statistic**\n\n    - $\\chi_0^2 = \\sum_{i=1}^k \\frac{(O_i-E_i)^2}{E_i}$\n\n- **p-Value**\n\n    - $p = \\text{P}[\\chi^2_{(r-1)(c-1)} \\ge \\chi^2_0]$\n\n- **Rejection Region**\n\n    -  Reject $H_0$ if $p < \\alpha$\n    \n## Test for Independence\n\n- If given the contingency table, we can enter it in a `matrix()` (see example) and use the `chisq.test()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(matrix_name)\n```\n:::\n\n\n\n- If given raw data, we can use the [`CrossTable()`](https://www.rdocumentation.org/packages/gmodels/versions/2.18.1.1/topics/CrossTable) function in the [`gmodels`](https://www.rdocumentation.org/packages/gmodels/versions/2.18.1.1) package.\n\n    - Note: this function replicates PROC FREQ from SAS :)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCrossTable(dataset_name$row_name, dataset_name$column_name], \n           prop.chisq= FALSE,  # turn off proportion contributed to chi-square statistic\n           prop.t = FALSE, # turn off total proportions\n           chisq = TRUE) # request chi-square test\n```\n:::\n\n\n\n## Test for Independence\n\n- In our example,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_table <- matrix(c(600, 63, 112, 144,\n                           720, 142, 355, 459,\n                           93, 51, 119, 127), \n                         nrow = 3, ncol = 4, byrow = T)\n# I prefer to include breaks to make it look like the table given just for checking purposes\n# make sure you edit the number of rows (nrow) and columns (ncol)!\n\nrownames(observed_table) <- c(\"Very Happy\", \"Pretty Happy\", \"Not Too Happy\") # name rows\ncolnames(observed_table) <- c(\"Married\", \"Widowed\", \"Divorced/Separated\", \"Never Married\") # name cols\n\nobserved_table # print table to make sure it is what we want\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Married Widowed Divorced/Separated Never Married\nVery Happy        600      63                112           144\nPretty Happy      720     142                355           459\nNot Too Happy      93      51                119           127\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(observed_table) # chi-squared test for independence\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  observed_table\nX-squared = 224.12, df = 6, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n## Test for Independence\n\n- **Hypotheses**\n\n    - $H_0:$ Happiness does not depend on marital status.\n    - $H_1:$ Happiness depends on marital status.\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2_0 = 224.116$\n    - $p < 0.001$\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$\n\n- **Conclusion/Interpretation**\n\n    - Reject $H_0$. \n    \n    - There is sufficient evidence to suggest that happiness depends on marital status.\n  \n## Test for Independence \n\n- To see how the `CrossTable()` function works, let's explore the Palmer penguin dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gmodels)\npenguins <- palmerpenguins::penguins \nCrossTable(penguins$species, penguins$sex, \n           prop.chisq= FALSE,  # turn off proportion contributed to chi-square statistic\n           prop.t = FALSE, # turn off total proportions\n           chisq = TRUE) # request chi-square test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n \n   Cell Contents\n|-------------------------|\n|                       N |\n|           N / Row Total |\n|           N / Col Total |\n|-------------------------|\n\n \nTotal Observations in Table:  333 \n\n \n                 | penguins$sex \npenguins$species |    female |      male | Row Total | \n-----------------|-----------|-----------|-----------|\n          Adelie |        73 |        73 |       146 | \n                 |     0.500 |     0.500 |     0.438 | \n                 |     0.442 |     0.435 |           | \n-----------------|-----------|-----------|-----------|\n       Chinstrap |        34 |        34 |        68 | \n                 |     0.500 |     0.500 |     0.204 | \n                 |     0.206 |     0.202 |           | \n-----------------|-----------|-----------|-----------|\n          Gentoo |        58 |        61 |       119 | \n                 |     0.487 |     0.513 |     0.357 | \n                 |     0.352 |     0.363 |           | \n-----------------|-----------|-----------|-----------|\n    Column Total |       165 |       168 |       333 | \n                 |     0.495 |     0.505 |           | \n-----------------|-----------|-----------|-----------|\n\n \nStatistics for All Table Factors\n\n\nPearson's Chi-squared test \n------------------------------------------------------------\nChi^2 =  0.04860717     d.f. =  2     p =  0.9759894 \n\n\n \n```\n\n\n:::\n:::\n\n\n\n\n## Test for Independence\n\n- **Hypotheses**\n\n    - $H_0:$ Biological sex of penguin depends on penguin species.\n    - $H_1:$ Biological sex of penguin does not depend on penguin species.\n\n- **Test Statistic and *p*-Value**\n\n    - $\\chi^2_0 = 0.049$\n    - $p = 0.976$\n\n- **Rejection Region**\n\n    - Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$\n\n- **Conclusion/Interpretation**\n\n    - Fail to reject $H_0$. There is not sufficient evidence to suggest that the biological sex of penguins depends on species of penguin.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}