{
  "hash": "e41d023fede6f13b3f458fee252853d6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**Review: Inferential Statistics & Two-Sample *t*-Tests**\"\nsubtitle: \"**STA4173: Biostatistics** <br> Spring 2025\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n  error: true\nformat: \n  revealjs:\n    code-overflow: wrap\n    df-print: paged\n    embed-resources: true\n    slide-number: false\n    width: 1600\n    height: 900\n    html-math-method: katex\n    theme:\n      - default\n      - sp25.scss\neditor: source\n---\n\n\n\n## **Introduction**\n\n- In the last lecture, we focused on *describing* data.\n    \n    - Continuous data: mean with standard deviation, median with interquartile range\n    - Categorical data: count with percentage\n\n- Today, we will focus on drawing *conclusions* about two population means using data.\n\n    - Confidence intervals\n    - Hypothesis testing\n    \n## **Confidence Intervals**\n\n::: {.callout-note}\n## Point Estimate\nThe single value of a statistic that estimates the value of a parameter.\n:::\n\n- Examples of point estimates:\n\n- It is necessary to know how good our estimation is, or to quantify our uncertainty. \n\n::: {.callout-note}\n## Confidence Interval\nA range of plausible values for the parameter based on values observed in the sample. \n\n$$\n\\text{estimate} \\pm \\text{margin of error}\n$$\n:::\n\n::: {.callout-note}\n## Level of Confidence\nThe probability that the interval will capture the true parameter value in repeated samples. i.e., the  success rate for the method.\n:::\n\n## **Confidence Intervals**\n\n<center><img src=\"images/L02a.png\"></center>\n\n## **Confidence Intervals**\n\n- Because CIs are a range of values, we will use interval notation,\n\n<center>(lower bound, upper bound)</center>\n\n- where\n    - lower bound = point estimate -- margin of error \n    - upper bound = point estimate + margin of error\n- Make sure to state your confidence intervals in numeric order.\n    - i.e., the lower bound must be the smaller number and the upper bound must be the larger number.\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n::: {.callout-note}\n## $(1-\\alpha)100\\%$ confidence interval for $\\mu_1-\\mu_2$\n$$\n(\\bar{x}_1 - \\bar{x}_2) \\pm t_{\\alpha/2} \\sqrt{\\frac{s_1^2 }{n_1} + \\frac{s_2^2}{n_2}}\n$$\nwhere $t_{\\alpha/2}$ has $\\text{min}(n_1-1, n_2-1)$ degrees of freedom. \n\n:::\n\n- To construct this interval, we require either:\n    - the two populations to be normally distributed or\n    - the sample sizes are sufficiently large ($n_1 \\ge 30$ and $n_2 \\ge 30$)\n\n- R syntax:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(continuous_variable ~ grouping_variable,\n       data = dataset_name,\n       conf.level = confidence_level) \n```\n:::\n\n\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n- Recall the Palmer penguin data,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins <- palmerpenguins::penguins\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"species\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"island\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"bill_length_mm\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bill_depth_mm\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"flipper_length_mm\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"body_mass_g\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"sex\"],\"name\":[7],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.1\",\"4\":\"18.7\",\"5\":\"181\",\"6\":\"3750\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.5\",\"4\":\"17.4\",\"5\":\"186\",\"6\":\"3800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"40.3\",\"4\":\"18.0\",\"5\":\"195\",\"6\":\"3250\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"36.7\",\"4\":\"19.3\",\"5\":\"193\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.3\",\"4\":\"20.6\",\"5\":\"190\",\"6\":\"3650\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.9\",\"4\":\"17.8\",\"5\":\"181\",\"6\":\"3625\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.2\",\"4\":\"19.6\",\"5\":\"195\",\"6\":\"4675\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"34.1\",\"4\":\"18.1\",\"5\":\"193\",\"6\":\"3475\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"42.0\",\"4\":\"20.2\",\"5\":\"190\",\"6\":\"4250\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"37.8\",\"4\":\"17.1\",\"5\":\"186\",\"6\":\"3300\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"37.8\",\"4\":\"17.3\",\"5\":\"180\",\"6\":\"3700\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"41.1\",\"4\":\"17.6\",\"5\":\"182\",\"6\":\"3200\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.6\",\"4\":\"21.2\",\"5\":\"191\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"34.6\",\"4\":\"21.1\",\"5\":\"198\",\"6\":\"4400\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"36.6\",\"4\":\"17.8\",\"5\":\"185\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.7\",\"4\":\"19.0\",\"5\":\"195\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"42.5\",\"4\":\"20.7\",\"5\":\"197\",\"6\":\"4500\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"34.4\",\"4\":\"18.4\",\"5\":\"184\",\"6\":\"3325\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"46.0\",\"4\":\"21.5\",\"5\":\"194\",\"6\":\"4200\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.8\",\"4\":\"18.3\",\"5\":\"174\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.7\",\"4\":\"18.7\",\"5\":\"180\",\"6\":\"3600\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.9\",\"4\":\"19.2\",\"5\":\"189\",\"6\":\"3800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.2\",\"4\":\"18.1\",\"5\":\"185\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.8\",\"4\":\"17.2\",\"5\":\"180\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.3\",\"4\":\"18.9\",\"5\":\"187\",\"6\":\"3800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"40.6\",\"4\":\"18.6\",\"5\":\"183\",\"6\":\"3550\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"40.5\",\"4\":\"17.9\",\"5\":\"187\",\"6\":\"3200\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.9\",\"4\":\"18.6\",\"5\":\"172\",\"6\":\"3150\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"40.5\",\"4\":\"18.9\",\"5\":\"180\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.5\",\"4\":\"16.7\",\"5\":\"178\",\"6\":\"3250\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.2\",\"4\":\"18.1\",\"5\":\"178\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.5\",\"4\":\"17.8\",\"5\":\"188\",\"6\":\"3300\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.9\",\"4\":\"18.9\",\"5\":\"184\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.4\",\"4\":\"17.0\",\"5\":\"195\",\"6\":\"3325\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.2\",\"4\":\"21.1\",\"5\":\"196\",\"6\":\"4150\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"38.8\",\"4\":\"20.0\",\"5\":\"190\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"42.2\",\"4\":\"18.5\",\"5\":\"180\",\"6\":\"3550\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.6\",\"4\":\"19.3\",\"5\":\"181\",\"6\":\"3300\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.8\",\"4\":\"19.1\",\"5\":\"184\",\"6\":\"4650\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.5\",\"4\":\"18.0\",\"5\":\"182\",\"6\":\"3150\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.8\",\"4\":\"18.4\",\"5\":\"195\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.0\",\"4\":\"18.5\",\"5\":\"186\",\"6\":\"3100\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"44.1\",\"4\":\"19.7\",\"5\":\"196\",\"6\":\"4400\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.0\",\"4\":\"16.9\",\"5\":\"185\",\"6\":\"3000\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.6\",\"4\":\"18.8\",\"5\":\"190\",\"6\":\"4600\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"41.1\",\"4\":\"19.0\",\"5\":\"182\",\"6\":\"3425\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.5\",\"4\":\"18.9\",\"5\":\"179\",\"6\":\"2975\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.0\",\"4\":\"17.9\",\"5\":\"190\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"42.3\",\"4\":\"21.2\",\"5\":\"191\",\"6\":\"4150\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"39.6\",\"4\":\"17.7\",\"5\":\"186\",\"6\":\"3500\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"40.1\",\"4\":\"18.9\",\"5\":\"188\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.0\",\"4\":\"17.9\",\"5\":\"190\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"42.0\",\"4\":\"19.5\",\"5\":\"200\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"34.5\",\"4\":\"18.1\",\"5\":\"187\",\"6\":\"2900\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.4\",\"4\":\"18.6\",\"5\":\"191\",\"6\":\"3700\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"39.0\",\"4\":\"17.5\",\"5\":\"186\",\"6\":\"3550\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"40.6\",\"4\":\"18.8\",\"5\":\"193\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"36.5\",\"4\":\"16.6\",\"5\":\"181\",\"6\":\"2850\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.6\",\"4\":\"19.1\",\"5\":\"194\",\"6\":\"3750\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.7\",\"4\":\"16.9\",\"5\":\"185\",\"6\":\"3150\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.3\",\"4\":\"21.1\",\"5\":\"195\",\"6\":\"4400\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.6\",\"4\":\"17.0\",\"5\":\"185\",\"6\":\"3600\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.1\",\"4\":\"18.2\",\"5\":\"192\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"36.4\",\"4\":\"17.1\",\"5\":\"184\",\"6\":\"2850\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.6\",\"4\":\"18.0\",\"5\":\"192\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.5\",\"4\":\"16.2\",\"5\":\"195\",\"6\":\"3350\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.1\",\"4\":\"19.1\",\"5\":\"188\",\"6\":\"4100\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"35.9\",\"4\":\"16.6\",\"5\":\"190\",\"6\":\"3050\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"41.8\",\"4\":\"19.4\",\"5\":\"198\",\"6\":\"4450\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"33.5\",\"4\":\"19.0\",\"5\":\"190\",\"6\":\"3600\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.7\",\"4\":\"18.4\",\"5\":\"190\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.6\",\"4\":\"17.2\",\"5\":\"196\",\"6\":\"3550\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"45.8\",\"4\":\"18.9\",\"5\":\"197\",\"6\":\"4150\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"35.5\",\"4\":\"17.5\",\"5\":\"190\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"42.8\",\"4\":\"18.5\",\"5\":\"195\",\"6\":\"4250\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"40.9\",\"4\":\"16.8\",\"5\":\"191\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"37.2\",\"4\":\"19.4\",\"5\":\"184\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"36.2\",\"4\":\"16.1\",\"5\":\"187\",\"6\":\"3550\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"42.1\",\"4\":\"19.1\",\"5\":\"195\",\"6\":\"4000\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"34.6\",\"4\":\"17.2\",\"5\":\"189\",\"6\":\"3200\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"42.9\",\"4\":\"17.6\",\"5\":\"196\",\"6\":\"4700\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"36.7\",\"4\":\"18.8\",\"5\":\"187\",\"6\":\"3800\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"35.1\",\"4\":\"19.4\",\"5\":\"193\",\"6\":\"4200\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.3\",\"4\":\"17.8\",\"5\":\"191\",\"6\":\"3350\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"41.3\",\"4\":\"20.3\",\"5\":\"194\",\"6\":\"3550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.3\",\"4\":\"19.5\",\"5\":\"190\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.9\",\"4\":\"18.6\",\"5\":\"189\",\"6\":\"3500\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"38.3\",\"4\":\"19.2\",\"5\":\"189\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"38.9\",\"4\":\"18.8\",\"5\":\"190\",\"6\":\"3600\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"35.7\",\"4\":\"18.0\",\"5\":\"202\",\"6\":\"3550\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"41.1\",\"4\":\"18.1\",\"5\":\"205\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"34.0\",\"4\":\"17.1\",\"5\":\"185\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.6\",\"4\":\"18.1\",\"5\":\"186\",\"6\":\"4450\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.2\",\"4\":\"17.3\",\"5\":\"187\",\"6\":\"3300\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.8\",\"4\":\"18.9\",\"5\":\"208\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"38.1\",\"4\":\"18.6\",\"5\":\"190\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.3\",\"4\":\"18.5\",\"5\":\"196\",\"6\":\"4350\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"33.1\",\"4\":\"16.1\",\"5\":\"178\",\"6\":\"2900\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"43.2\",\"4\":\"18.5\",\"5\":\"192\",\"6\":\"4100\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"35.0\",\"4\":\"17.9\",\"5\":\"192\",\"6\":\"3725\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"41.0\",\"4\":\"20.0\",\"5\":\"203\",\"6\":\"4725\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.7\",\"4\":\"16.0\",\"5\":\"183\",\"6\":\"3075\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.8\",\"4\":\"20.0\",\"5\":\"190\",\"6\":\"4250\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"37.9\",\"4\":\"18.6\",\"5\":\"193\",\"6\":\"2925\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"39.7\",\"4\":\"18.9\",\"5\":\"184\",\"6\":\"3550\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.6\",\"4\":\"17.2\",\"5\":\"199\",\"6\":\"3750\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.2\",\"4\":\"20.0\",\"5\":\"190\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.1\",\"4\":\"17.0\",\"5\":\"181\",\"6\":\"3175\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"43.2\",\"4\":\"19.0\",\"5\":\"197\",\"6\":\"4775\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"38.1\",\"4\":\"16.5\",\"5\":\"198\",\"6\":\"3825\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"45.6\",\"4\":\"20.3\",\"5\":\"191\",\"6\":\"4600\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"39.7\",\"4\":\"17.7\",\"5\":\"193\",\"6\":\"3200\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"42.2\",\"4\":\"19.5\",\"5\":\"197\",\"6\":\"4275\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"39.6\",\"4\":\"20.7\",\"5\":\"191\",\"6\":\"3900\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Biscoe\",\"3\":\"42.7\",\"4\":\"18.3\",\"5\":\"196\",\"6\":\"4075\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.6\",\"4\":\"17.0\",\"5\":\"188\",\"6\":\"2900\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"37.3\",\"4\":\"20.5\",\"5\":\"199\",\"6\":\"3775\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"35.7\",\"4\":\"17.0\",\"5\":\"189\",\"6\":\"3350\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"41.1\",\"4\":\"18.6\",\"5\":\"189\",\"6\":\"3325\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"36.2\",\"4\":\"17.2\",\"5\":\"187\",\"6\":\"3150\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"37.7\",\"4\":\"19.8\",\"5\":\"198\",\"6\":\"3500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"40.2\",\"4\":\"17.0\",\"5\":\"176\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"41.4\",\"4\":\"18.5\",\"5\":\"202\",\"6\":\"3875\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"35.2\",\"4\":\"15.9\",\"5\":\"186\",\"6\":\"3050\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"40.6\",\"4\":\"19.0\",\"5\":\"199\",\"6\":\"4000\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.8\",\"4\":\"17.6\",\"5\":\"191\",\"6\":\"3275\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"41.5\",\"4\":\"18.3\",\"5\":\"195\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"39.0\",\"4\":\"17.1\",\"5\":\"191\",\"6\":\"3050\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"44.1\",\"4\":\"18.0\",\"5\":\"210\",\"6\":\"4000\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"38.5\",\"4\":\"17.9\",\"5\":\"190\",\"6\":\"3325\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Torgersen\",\"3\":\"43.1\",\"4\":\"19.2\",\"5\":\"197\",\"6\":\"3500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.8\",\"4\":\"18.5\",\"5\":\"193\",\"6\":\"3500\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.5\",\"4\":\"18.5\",\"5\":\"199\",\"6\":\"4475\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"38.1\",\"4\":\"17.6\",\"5\":\"187\",\"6\":\"3425\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"41.1\",\"4\":\"17.5\",\"5\":\"190\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"35.6\",\"4\":\"17.5\",\"5\":\"191\",\"6\":\"3175\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.2\",\"4\":\"20.1\",\"5\":\"200\",\"6\":\"3975\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.0\",\"4\":\"16.5\",\"5\":\"185\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.7\",\"4\":\"17.9\",\"5\":\"193\",\"6\":\"4250\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.2\",\"4\":\"17.1\",\"5\":\"193\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.6\",\"4\":\"17.2\",\"5\":\"187\",\"6\":\"3475\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"32.1\",\"4\":\"15.5\",\"5\":\"188\",\"6\":\"3050\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"40.7\",\"4\":\"17.0\",\"5\":\"190\",\"6\":\"3725\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.3\",\"4\":\"16.8\",\"5\":\"192\",\"6\":\"3000\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.0\",\"4\":\"18.7\",\"5\":\"185\",\"6\":\"3650\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"39.2\",\"4\":\"18.6\",\"5\":\"190\",\"6\":\"4250\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.6\",\"4\":\"18.4\",\"5\":\"184\",\"6\":\"3475\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.0\",\"4\":\"17.8\",\"5\":\"195\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"37.8\",\"4\":\"18.1\",\"5\":\"193\",\"6\":\"3750\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"36.0\",\"4\":\"17.1\",\"5\":\"187\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Adelie\",\"2\":\"Dream\",\"3\":\"41.5\",\"4\":\"18.5\",\"5\":\"201\",\"6\":\"4000\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.1\",\"4\":\"13.2\",\"5\":\"211\",\"6\":\"4500\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.0\",\"4\":\"16.3\",\"5\":\"230\",\"6\":\"5700\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.7\",\"4\":\"14.1\",\"5\":\"210\",\"6\":\"4450\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.0\",\"4\":\"15.2\",\"5\":\"218\",\"6\":\"5700\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.6\",\"4\":\"14.5\",\"5\":\"215\",\"6\":\"5400\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.5\",\"4\":\"13.5\",\"5\":\"210\",\"6\":\"4550\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.4\",\"4\":\"14.6\",\"5\":\"211\",\"6\":\"4800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.7\",\"4\":\"15.3\",\"5\":\"219\",\"6\":\"5200\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.3\",\"4\":\"13.4\",\"5\":\"209\",\"6\":\"4400\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.8\",\"4\":\"15.4\",\"5\":\"215\",\"6\":\"5150\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"40.9\",\"4\":\"13.7\",\"5\":\"214\",\"6\":\"4650\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.0\",\"4\":\"16.1\",\"5\":\"216\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.5\",\"4\":\"13.7\",\"5\":\"214\",\"6\":\"4650\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.4\",\"4\":\"14.6\",\"5\":\"213\",\"6\":\"5850\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.8\",\"4\":\"14.6\",\"5\":\"210\",\"6\":\"4200\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.3\",\"4\":\"15.7\",\"5\":\"217\",\"6\":\"5850\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"42.0\",\"4\":\"13.5\",\"5\":\"210\",\"6\":\"4150\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.2\",\"4\":\"15.2\",\"5\":\"221\",\"6\":\"6300\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.2\",\"4\":\"14.5\",\"5\":\"209\",\"6\":\"4800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.7\",\"4\":\"15.1\",\"5\":\"222\",\"6\":\"5350\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.2\",\"4\":\"14.3\",\"5\":\"218\",\"6\":\"5700\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.1\",\"4\":\"14.5\",\"5\":\"215\",\"6\":\"5000\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.5\",\"4\":\"14.5\",\"5\":\"213\",\"6\":\"4400\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.3\",\"4\":\"15.8\",\"5\":\"215\",\"6\":\"5050\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"42.9\",\"4\":\"13.1\",\"5\":\"215\",\"6\":\"5000\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.1\",\"4\":\"15.1\",\"5\":\"215\",\"6\":\"5100\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.5\",\"4\":\"14.3\",\"5\":\"216\",\"6\":\"4100\",\"7\":\"NA\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.8\",\"4\":\"15.0\",\"5\":\"215\",\"6\":\"5650\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.2\",\"4\":\"14.3\",\"5\":\"210\",\"6\":\"4600\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.0\",\"4\":\"15.3\",\"5\":\"220\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.3\",\"4\":\"15.3\",\"5\":\"222\",\"6\":\"5250\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"42.8\",\"4\":\"14.2\",\"5\":\"209\",\"6\":\"4700\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.1\",\"4\":\"14.5\",\"5\":\"207\",\"6\":\"5050\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"59.6\",\"4\":\"17.0\",\"5\":\"230\",\"6\":\"6050\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.1\",\"4\":\"14.8\",\"5\":\"220\",\"6\":\"5150\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.4\",\"4\":\"16.3\",\"5\":\"220\",\"6\":\"5400\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"42.6\",\"4\":\"13.7\",\"5\":\"213\",\"6\":\"4950\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.4\",\"4\":\"17.3\",\"5\":\"219\",\"6\":\"5250\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.0\",\"4\":\"13.6\",\"5\":\"208\",\"6\":\"4350\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.7\",\"4\":\"15.7\",\"5\":\"208\",\"6\":\"5350\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"42.7\",\"4\":\"13.7\",\"5\":\"208\",\"6\":\"3950\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.6\",\"4\":\"16.0\",\"5\":\"225\",\"6\":\"5700\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.3\",\"4\":\"13.7\",\"5\":\"210\",\"6\":\"4300\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.6\",\"4\":\"15.0\",\"5\":\"216\",\"6\":\"4750\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.5\",\"4\":\"15.9\",\"5\":\"222\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.6\",\"4\":\"13.9\",\"5\":\"217\",\"6\":\"4900\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.5\",\"4\":\"13.9\",\"5\":\"210\",\"6\":\"4200\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.5\",\"4\":\"15.9\",\"5\":\"225\",\"6\":\"5400\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.9\",\"4\":\"13.3\",\"5\":\"213\",\"6\":\"5100\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.2\",\"4\":\"15.8\",\"5\":\"215\",\"6\":\"5300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.6\",\"4\":\"14.2\",\"5\":\"210\",\"6\":\"4850\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.5\",\"4\":\"14.1\",\"5\":\"220\",\"6\":\"5300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.1\",\"4\":\"14.4\",\"5\":\"210\",\"6\":\"4400\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.1\",\"4\":\"15.0\",\"5\":\"225\",\"6\":\"5000\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.5\",\"4\":\"14.4\",\"5\":\"217\",\"6\":\"4900\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.0\",\"4\":\"15.4\",\"5\":\"220\",\"6\":\"5050\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.8\",\"4\":\"13.9\",\"5\":\"208\",\"6\":\"4300\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.5\",\"4\":\"15.0\",\"5\":\"220\",\"6\":\"5000\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.2\",\"4\":\"14.5\",\"5\":\"208\",\"6\":\"4450\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.4\",\"4\":\"15.3\",\"5\":\"224\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.3\",\"4\":\"13.8\",\"5\":\"208\",\"6\":\"4200\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.2\",\"4\":\"14.9\",\"5\":\"221\",\"6\":\"5300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.7\",\"4\":\"13.9\",\"5\":\"214\",\"6\":\"4400\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"54.3\",\"4\":\"15.7\",\"5\":\"231\",\"6\":\"5650\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.8\",\"4\":\"14.2\",\"5\":\"219\",\"6\":\"4700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.8\",\"4\":\"16.8\",\"5\":\"230\",\"6\":\"5700\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.2\",\"4\":\"14.4\",\"5\":\"214\",\"6\":\"4650\",\"7\":\"NA\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.5\",\"4\":\"16.2\",\"5\":\"229\",\"6\":\"5800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.5\",\"4\":\"14.2\",\"5\":\"220\",\"6\":\"4700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.7\",\"4\":\"15.0\",\"5\":\"223\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.7\",\"4\":\"15.0\",\"5\":\"216\",\"6\":\"4750\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.4\",\"4\":\"15.6\",\"5\":\"221\",\"6\":\"5000\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.2\",\"4\":\"15.6\",\"5\":\"221\",\"6\":\"5100\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.5\",\"4\":\"14.8\",\"5\":\"217\",\"6\":\"5200\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.4\",\"4\":\"15.0\",\"5\":\"216\",\"6\":\"4700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.6\",\"4\":\"16.0\",\"5\":\"230\",\"6\":\"5800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.5\",\"4\":\"14.2\",\"5\":\"209\",\"6\":\"4600\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"51.1\",\"4\":\"16.3\",\"5\":\"220\",\"6\":\"6000\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.2\",\"4\":\"13.8\",\"5\":\"215\",\"6\":\"4750\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.2\",\"4\":\"16.4\",\"5\":\"223\",\"6\":\"5950\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.1\",\"4\":\"14.5\",\"5\":\"212\",\"6\":\"4625\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"52.5\",\"4\":\"15.6\",\"5\":\"221\",\"6\":\"5450\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.4\",\"4\":\"14.6\",\"5\":\"212\",\"6\":\"4725\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.0\",\"4\":\"15.9\",\"5\":\"224\",\"6\":\"5350\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.9\",\"4\":\"13.8\",\"5\":\"212\",\"6\":\"4750\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.8\",\"4\":\"17.3\",\"5\":\"228\",\"6\":\"5600\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.4\",\"4\":\"14.4\",\"5\":\"218\",\"6\":\"4600\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"51.3\",\"4\":\"14.2\",\"5\":\"218\",\"6\":\"5300\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.5\",\"4\":\"14.0\",\"5\":\"212\",\"6\":\"4875\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"52.1\",\"4\":\"17.0\",\"5\":\"230\",\"6\":\"5550\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.5\",\"4\":\"15.0\",\"5\":\"218\",\"6\":\"4950\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"52.2\",\"4\":\"17.1\",\"5\":\"228\",\"6\":\"5400\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.5\",\"4\":\"14.5\",\"5\":\"212\",\"6\":\"4750\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.5\",\"4\":\"16.1\",\"5\":\"224\",\"6\":\"5650\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.5\",\"4\":\"14.7\",\"5\":\"214\",\"6\":\"4850\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.8\",\"4\":\"15.7\",\"5\":\"226\",\"6\":\"5200\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.4\",\"4\":\"15.8\",\"5\":\"216\",\"6\":\"4925\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.9\",\"4\":\"14.6\",\"5\":\"222\",\"6\":\"4875\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.4\",\"4\":\"14.4\",\"5\":\"203\",\"6\":\"4625\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"51.1\",\"4\":\"16.5\",\"5\":\"225\",\"6\":\"5250\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.5\",\"4\":\"15.0\",\"5\":\"219\",\"6\":\"4850\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"55.9\",\"4\":\"17.0\",\"5\":\"228\",\"6\":\"5600\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.2\",\"4\":\"15.5\",\"5\":\"215\",\"6\":\"4975\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.1\",\"4\":\"15.0\",\"5\":\"228\",\"6\":\"5500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.3\",\"4\":\"13.8\",\"5\":\"216\",\"6\":\"4725\",\"7\":\"NA\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.8\",\"4\":\"16.1\",\"5\":\"215\",\"6\":\"5500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"41.7\",\"4\":\"14.7\",\"5\":\"210\",\"6\":\"4700\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"53.4\",\"4\":\"15.8\",\"5\":\"219\",\"6\":\"5500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.3\",\"4\":\"14.0\",\"5\":\"208\",\"6\":\"4575\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.1\",\"4\":\"15.1\",\"5\":\"209\",\"6\":\"5500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.5\",\"4\":\"15.2\",\"5\":\"216\",\"6\":\"5000\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.8\",\"4\":\"15.9\",\"5\":\"229\",\"6\":\"5950\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"43.5\",\"4\":\"15.2\",\"5\":\"213\",\"6\":\"4650\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"51.5\",\"4\":\"16.3\",\"5\":\"230\",\"6\":\"5500\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.2\",\"4\":\"14.1\",\"5\":\"217\",\"6\":\"4375\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"55.1\",\"4\":\"16.0\",\"5\":\"230\",\"6\":\"5850\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"44.5\",\"4\":\"15.7\",\"5\":\"217\",\"6\":\"4875\",\"7\":\"NA\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"48.8\",\"4\":\"16.2\",\"5\":\"222\",\"6\":\"6000\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"47.2\",\"4\":\"13.7\",\"5\":\"214\",\"6\":\"4925\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"NA\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"46.8\",\"4\":\"14.3\",\"5\":\"215\",\"6\":\"4850\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"50.4\",\"4\":\"15.7\",\"5\":\"222\",\"6\":\"5750\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"45.2\",\"4\":\"14.8\",\"5\":\"212\",\"6\":\"5200\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Gentoo\",\"2\":\"Biscoe\",\"3\":\"49.9\",\"4\":\"16.1\",\"5\":\"213\",\"6\":\"5400\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.5\",\"4\":\"17.9\",\"5\":\"192\",\"6\":\"3500\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.0\",\"4\":\"19.5\",\"5\":\"196\",\"6\":\"3900\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.3\",\"4\":\"19.2\",\"5\":\"193\",\"6\":\"3650\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.4\",\"4\":\"18.7\",\"5\":\"188\",\"6\":\"3525\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.7\",\"4\":\"19.8\",\"5\":\"197\",\"6\":\"3725\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.2\",\"4\":\"17.8\",\"5\":\"198\",\"6\":\"3950\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.1\",\"4\":\"18.2\",\"5\":\"178\",\"6\":\"3250\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.3\",\"4\":\"18.2\",\"5\":\"197\",\"6\":\"3750\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.0\",\"4\":\"18.9\",\"5\":\"195\",\"6\":\"4150\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.3\",\"4\":\"19.9\",\"5\":\"198\",\"6\":\"3700\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.6\",\"4\":\"17.8\",\"5\":\"193\",\"6\":\"3800\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.7\",\"4\":\"20.3\",\"5\":\"194\",\"6\":\"3775\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"47.0\",\"4\":\"17.3\",\"5\":\"185\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.0\",\"4\":\"18.1\",\"5\":\"201\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.9\",\"4\":\"17.1\",\"5\":\"190\",\"6\":\"3575\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.5\",\"4\":\"19.6\",\"5\":\"201\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.3\",\"4\":\"20.0\",\"5\":\"197\",\"6\":\"3300\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"58.0\",\"4\":\"17.8\",\"5\":\"181\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.4\",\"4\":\"18.6\",\"5\":\"190\",\"6\":\"3450\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.2\",\"4\":\"18.2\",\"5\":\"195\",\"6\":\"4400\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"42.4\",\"4\":\"17.3\",\"5\":\"181\",\"6\":\"3600\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"48.5\",\"4\":\"17.5\",\"5\":\"191\",\"6\":\"3400\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"43.2\",\"4\":\"16.6\",\"5\":\"187\",\"6\":\"2900\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.6\",\"4\":\"19.4\",\"5\":\"193\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.7\",\"4\":\"17.9\",\"5\":\"195\",\"6\":\"3300\",\"7\":\"female\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.0\",\"4\":\"19.0\",\"5\":\"197\",\"6\":\"4150\",\"7\":\"male\",\"8\":\"2007\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.5\",\"4\":\"18.4\",\"5\":\"200\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.5\",\"4\":\"19.0\",\"5\":\"200\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.4\",\"4\":\"17.8\",\"5\":\"191\",\"6\":\"3700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.8\",\"4\":\"20.0\",\"5\":\"205\",\"6\":\"4550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"40.9\",\"4\":\"16.6\",\"5\":\"187\",\"6\":\"3200\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"54.2\",\"4\":\"20.8\",\"5\":\"201\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"42.5\",\"4\":\"16.7\",\"5\":\"187\",\"6\":\"3350\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.0\",\"4\":\"18.8\",\"5\":\"203\",\"6\":\"4100\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.7\",\"4\":\"18.6\",\"5\":\"195\",\"6\":\"3600\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"47.5\",\"4\":\"16.8\",\"5\":\"199\",\"6\":\"3900\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"47.6\",\"4\":\"18.3\",\"5\":\"195\",\"6\":\"3850\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.0\",\"4\":\"20.7\",\"5\":\"210\",\"6\":\"4800\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.9\",\"4\":\"16.6\",\"5\":\"192\",\"6\":\"2700\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"53.5\",\"4\":\"19.9\",\"5\":\"205\",\"6\":\"4500\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.0\",\"4\":\"19.5\",\"5\":\"210\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.2\",\"4\":\"17.5\",\"5\":\"187\",\"6\":\"3650\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.9\",\"4\":\"19.1\",\"5\":\"196\",\"6\":\"3550\",\"7\":\"male\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.5\",\"4\":\"17.0\",\"5\":\"196\",\"6\":\"3500\",\"7\":\"female\",\"8\":\"2008\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.9\",\"4\":\"17.9\",\"5\":\"196\",\"6\":\"3675\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.8\",\"4\":\"18.5\",\"5\":\"201\",\"6\":\"4450\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.1\",\"4\":\"17.9\",\"5\":\"190\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.0\",\"4\":\"19.6\",\"5\":\"212\",\"6\":\"4300\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.5\",\"4\":\"18.7\",\"5\":\"187\",\"6\":\"3250\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.8\",\"4\":\"17.3\",\"5\":\"198\",\"6\":\"3675\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"48.1\",\"4\":\"16.4\",\"5\":\"199\",\"6\":\"3325\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.4\",\"4\":\"19.0\",\"5\":\"201\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.7\",\"4\":\"17.3\",\"5\":\"193\",\"6\":\"3600\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.7\",\"4\":\"19.7\",\"5\":\"203\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"42.5\",\"4\":\"17.3\",\"5\":\"187\",\"6\":\"3350\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"52.2\",\"4\":\"18.8\",\"5\":\"197\",\"6\":\"3450\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.2\",\"4\":\"16.6\",\"5\":\"191\",\"6\":\"3250\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.3\",\"4\":\"19.9\",\"5\":\"203\",\"6\":\"4050\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.2\",\"4\":\"18.8\",\"5\":\"202\",\"6\":\"3800\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.6\",\"4\":\"19.4\",\"5\":\"194\",\"6\":\"3525\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"51.9\",\"4\":\"19.5\",\"5\":\"206\",\"6\":\"3950\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"46.8\",\"4\":\"16.5\",\"5\":\"189\",\"6\":\"3650\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"45.7\",\"4\":\"17.0\",\"5\":\"195\",\"6\":\"3650\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"55.8\",\"4\":\"19.8\",\"5\":\"207\",\"6\":\"4000\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"43.5\",\"4\":\"18.1\",\"5\":\"202\",\"6\":\"3400\",\"7\":\"female\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"49.6\",\"4\":\"18.2\",\"5\":\"193\",\"6\":\"3775\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.8\",\"4\":\"19.0\",\"5\":\"210\",\"6\":\"4100\",\"7\":\"male\",\"8\":\"2009\"},{\"1\":\"Chinstrap\",\"2\":\"Dream\",\"3\":\"50.2\",\"4\":\"18.7\",\"5\":\"198\",\"6\":\"3775\",\"7\":\"female\",\"8\":\"2009\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n- Let's find the 95% confidence interval for the difference in average weight (*body_mass_g*) between male and female (*sex*) penguins.\n\n- Remember the R syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(continuous_variable ~ grouping_variable,\n       data = dataset_name,\n       conf.level = confidence_level) \n```\n:::\n\n\n\n- What is the continuous variable?\n\n- What is the grouping variable?\n\n- What is the dataset name?\n\n- What is the confidence level?\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n- Let's find the 95% confidence interval for the difference in weight (*body_mass_g*) between male and female penguins.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body_mass_g ~ sex,\n       data = penguins,\n       conf.level = 0.95) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body_mass_g by sex\nt = -8.5545, df = 323.9, p-value = 4.794e-16\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -840.5783 -526.2453\nsample estimates:\nmean in group female   mean in group male \n            3862.273             4545.685 \n```\n\n\n:::\n:::\n\n\n\n- Thus, the 95% confidence interval for $\\mu_F - \\mu_M$ is (-840.6, -526.2).\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n- What about the 99% confidence interval for the difference in weight (*body_mass_g*) between male and female penguins?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body_mass_g ~ sex,\n       data = penguins,\n       conf.level = 0.99) \n```\n:::\n\n\n\n- What do you expect? Recall that the 95% CI was (-840.6, -526.2).\n\n## **Confidence Interval for $\\mathbf{\\boldsymbol \\mu_1-\\boldsymbol\\mu_2}$**\n\n- What about the 99% confidence interval for the difference in weight (*body_mass_g*) between male and female penguins?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body_mass_g ~ sex,\n       data = penguins,\n       conf.level = 0.99) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body_mass_g by sex\nt = -8.5545, df = 323.9, p-value = 4.794e-16\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n99 percent confidence interval:\n -890.4112 -476.4124\nsample estimates:\nmean in group female   mean in group male \n            3862.273             4545.685 \n```\n\n\n:::\n:::\n\n\n\n- Thus, the 99% confidence interval for $\\mu_F - \\mu_M$ is (-890.4, -476.4).\n    - Recall that the 95% CI was (-840.6, -526.2).\n\n## **Hypothesis Testing**\n\n- A friend of yours wants to play a simple coin-flipping game. \n    - If the coin comes up heads, you win; if it comes up tails, your friend wins. \n    - Suppose the outcome of five plays of the game is T, T, T, T, T. \n    - Is your friend cheating?\n    \n## **Hypothesis Testing**\n\n- A friend of yours wants to play a simple coin-flipping game. \n    - If the coin comes up heads, you win; if it comes up tails, your friend wins. \n    - Suppose the outcome of five plays of the game is T, T, T, T, T. \n    - Is your friend cheating?\n        - We know the probability of flipping a tail is 0.5.\n        - We can compute the probability of flipping five tails in a row.\n        \n$$\n\\begin{align*}\n     P[\\text{T, T, T, T, T}] &=  0.5 \\times 0.5 \\times 0.5 \\times 0.5 \\times 0.5 \\\\\n     &= 0.03125\n\\end{align*}\n$$ \n\n- **Is this probability low enough to believe your friend is cheating?**\n\n## **Hypothesis Testing**\n\n::: {.callout-note}\n## Hypothesis Testing \nA procedure, based on sample evidence and probability, used to test statements regarding a characteristic of one or more populations.\n:::\n\n- **Steps in hypothesis testing**\n\n    1. Make a statement regarding the nature of the population.\n    \n    2. Collect evidence (sample data) to test the statement. \n    \n    3. Analyze the data to assess the plausibility of the statement.\n\n- Note: if we have population parameters available, we do not need to perform a hypothesis test.\n\n## **Hypothesis Testing: Hypotheses**\n\n::: {.callout-note}\n## Hypothesis \nA statement regarding a characteristic of one or more populations.\n:::\n\n- In hypothesis testing, we have two hypotheses: the null and the alternative. \n\n::: {.callout-note}\n## Null hypothesis, $H_0$ \nA statement to be tested. \n\n- This is a statement of no change, no effect, or no difference. \n- It is assumed true until evidence indicates otherwise.\n:::\n\n::: {.callout-note}\n## Alternative hypothesis, $H_1$ \nA statement that we are trying to find evidence to support.\n:::\n\n## **Hypothesis Testing: Hypotheses**\n\n- **One sample tests**:\n    - Two-tailed test\n        - $H_0:$ parameter = some value\n        - $H_1:$ parameter $\\ne$ some value\n    - Left-tailed test\n        - $H_0:$ parameter $\\ge$ some value\n        - $H_1:$ parameter $<$ some value\n    - Right-tailed test\n        - $H_0:$ parameter $\\le$ some value\n        - $H_1:$ parameter $>$ some value \n\n## **Hypothesis Testing: Hypotheses**\n\n- **Two sample tests**\n    - Two-tailed test\n        - $H_0:$ parameter~1~ -- parameter~2~ = 0\n        - $H_1:$ parameter~1~ -- parameter~2~ $\\ne$ 0\n    - Left-tailed test\n        - $H_0:$ parameter~1~ -- parameter~2~  $\\ge$ 0\n        - $H_1:$ parameter~1~ -- parameter~2~ $<$ 0\n    - Right-tailed test\n        - $H_0:$ parameter~1~ -- parameter~2~ $\\le$ 0\n        - $H_1:$ parameter~1~ -- parameter~2~ $>$ 0\n\n## **Hypothesis Testing: Errors**\n\n- We use data to draw conclusions about hypotheses.\n    - We will either *reject* or *fail to reject* the null ($H_0$).\n- If we draw the wrong conclusion, we make an error.\n- These can be classified as Type I ($\\alpha$) or Type II ($\\beta$) errors.\n    - $\\alpha$ and $\\beta$ are probabilities (i.e., are between 0 and 1).\n\n<center><img src=\"images/L02b.png\"></center>\n\n## **Hypothesis Testing: Errors**\n\n- As stated earlier, Type I ($\\alpha$) and Type II ($\\beta$) errors are probabilities.\n    - $\\alpha = \\text{P}[\\text{reject } H_0 \\text{ when } H_0 \\text{ is true}]$\n    - $\\beta = \\text{P}[\\text{fail to reject } H_0 \\text{ when } H_1 \\text{ is true}]$\n- We also call $\\alpha$ the level of significance. \n- We should choose $\\alpha$ based on the level of error we are willing to withstand in the experiment.\n    - The $\\alpha$ that is commonly used is $\\alpha=0.05$.\n    - Sometimes, smaller $\\alpha$ is used. e.g., clinical trial $\\to$  $\\alpha=0.01$.\n- For a fixed sample size ($n$), $\\alpha$ and $\\beta$ are inversely related.\n\n## **Hypothesis Testing: Test Statistics**\n\n- After stating our hypotheses, we will construct a test statistic. \n- The choice of test statistic depends on:\n    1.  The hypotheses being tested.\n    2. Assumptions made about the data.\n- The value of the test statistic depends on the sample data. \n    -  If we were to draw a different sample, we would find a different value for the test statistic.\n- We will use the test statistic on our way to drawing conclusions about the hypotheses.\n\n## **Hypothesis Testing: *p*-Values**\n\n::: {.callout-note}\n## *p*-value \nThe probability of observing what we've observed or something more extreme, assuming the null hypothesis is true.\n:::\n\n- After constructing test statistics, we will find the corresponding *p*-value.\n- Finding a *p*-value depends on the distribution being used. \n- We will compare the *p*-value to $\\alpha$ in order to draw conclusions.\n    - Reject $H_0$ if $p < \\alpha$.\n\n## **Hypothesis Testing: Conclusions and Interpretations**\n\n- Once we've found the *p*-value, we can draw a conclusion. \n    - If $p < \\alpha$, we **reject** $H_0$.\n        -  There is sufficient evidence to suggest that $H_1$ is true.\n    - If $p \\ge \\alpha$, we **fail to reject** $H_0$.\n        - There is <u>not</u> sufficient evidence to suggest that $H_1$ is true.\n- Take aways:\n    - <u>**We never \"accept\" the null.**</u>\n    - We <u>*always*</u> interpret in terms of $H_1$.\n    \n## **Two-Sample *t*-Test**\n\n::: {.callout-note}\n## Hypothesis Test for Two Independent Means\nHypotheses\n\n- $H_0:$ $\\mu_1-\\mu_2 = \\mu_0$ $|$ $H_0:$ $\\mu_1-\\mu_2 \\le \\mu_0$ | $H_0:$ $\\mu_1-\\mu_2 \\ge \\mu_0$\n- $H_1:$ $\\mu_1-\\mu_2 \\ne \\mu_0$ | $H_0:$ $\\mu_1 - \\mu_2 > \\mu_0$ | $H_1:$ $\\mu_1 - \\mu_2 < \\mu_0$ \n\nTest Statistic\n$$\nt_0 = \\frac{(\\bar{x}_1-\\bar{x}_2)-\\mu_0}{\\sqrt{\\frac{s_1^2}{n}+\\frac{s_2^2}{n}}}\n$$\n\n*p*-Value\n\n- $p = 2 P[t \\ge |t_0|]$ | $p = P[t \\ge |t_0|]$ | $p = P[t \\le |t_0|]$\n\nRejection Region\n\n- Reject $H_0$ if $p < \\alpha$.\n\nConclusion/Interpretation\n\n- [Reject or fail to reject] $H_0$.\n\n- There [is or is not] sufficient evidence to suggest [alternative hypothesis in words].\n\n:::\n\n## **Two-Sample *t*-Test**\n\n- R syntax:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(continuous_variable ~ grouping_variable,\n       data = dataset_name,\n       mu = hypothesized_difference,\n       alternative = alternative)\n```\n:::\n\n\n\n- Important!!\n    - We are estimating $\\mu_1 - \\mu_2$, but R is going to subtract in alphabetical or numeric order of the grouping variable.\n        - e.g., if we have \"Male\" and \"Female\", it will estimate $\\mu_{\\text{Female}} - \\mu_{\\text{Male}}$.\n        - e.g., if we have \"110\" and \"5\", it will estimate $\\mu_{5} - \\mu_{110}$.\n        - In the case of two-tailed tets, this does not matter... but beware when doing a one-tailed test!\n\n## **Two-Sample *t*-Test: Example**\n\n- Consider the penguin data. Is there a significant difference in weight (*body_mass_g*) between male and female penguins? Test at the $\\alpha=0.05$ level.\n\n- Remember the `R` syntax:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(continuous_variable ~ grouping_variable,\n       data = dataset_name,\n       mu = hypothesized_difference,\n       alternative = alternative)\n```\n:::\n\n\n\n- What is the continuous variable?\n\n- What is the grouping variable?\n\n- What is the dataset name?\n\n- What is the hypothesized difference?\n\n- What is the alternative?\n\n## **Two-Sample *t*-Test: Example**\n\n- Consider the penguin data. Is there a significant difference in weight (*body_mass_g*) between male and female penguins? Test at the $\\alpha=0.05$ level.\n\n- Remember the `R` syntax:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(body_mass_g ~ sex,\n       data = penguins,\n       mu = 0,\n       alternative = \"two\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  body_mass_g by sex\nt = -8.5545, df = 323.9, p-value = 4.794e-16\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -840.5783 -526.2453\nsample estimates:\nmean in group female   mean in group male \n            3862.273             4545.685 \n```\n\n\n:::\n:::\n\n\n\n- Is this a significant difference?\n\n## **Two-Sample *t*-Test: Example**\n\n**Hypotheses**\n\n- $H_0:$ $\\mu_1-\\mu_2 = 0$\n- $H_1:$ $\\mu_1-\\mu_2 \\ne 0$ \n\n**Test Statistic and *p*-Value**\n\n- $t_0 = -8.55$\n- $p < 0.001$\n\n**Rejection Region**\n\n- Reject $H_0$ if $p < \\alpha$; $\\alpha=0.05$.\n\n**Conclusion/Interpretation**\n\n- Reject $H_0$.\n\n- There is sufficient evidence to suggest that male and female penguins have different weights.\n    \n\n## **Hypothesis Testing: Practical vs. Statistical Significance**\n\n- Hypothesis testing depends on sample size.\n- As the sample size increases, our *p*-values decrease necessarily. \n- As *p*-values decrease, we are more likely to reject the null hypothesis.\n- We must ask ourselves if the value we are testing against makes practical sense. \n    - A new weight loss medication where the average amount of weight loss was 1 lb over 6 months.\n    - A new weight loss medication where the average amount of weight lost was 15 lb over 6 months.\n    - A new teaching method that raised final exam scores by 2 points.\n    - A new teaching method that raised final exam scores by 15 points.\n\n## **Wrap Up**\n\n- Today we reviewed statistical inference.\n    - Confidence intervals\n    - Hypothesis testing\n    \n- Get to know you quiz - complete with RStudio - due <u>today</u>.\n\n- Next meeting: how to conceptualize research questions; dependent *t*-test.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}